### ISSUE TITLE
Getting Error While running large proteins!!

### ISSUE THREAD

**Issue by RajShekhorRoy** [zw2x/glinter#1]
Hi,

I was running Glinter for 3 large targets among which 2 of them around 700residues and one of them is 621 residues. Is there residue lenght threshold more than which Glinter fails?

**Comment by zw2x** [comment]
Hi,

ESM-MSA Transformer has a length threshold ~1024 residues. So the overall number of residues of the input multimer should be less than that.

**Comment by RajShekhorRoy** [comment]
Ok, so the threshold for homodimers would be around 512 residue lengths for each. One follow-up question is, is there any possibility of the heterodimer bug fix, any time soon?.

**Comment by zw2x** [comment]
Yes.
The heterodimer pipeline should be fine if you use this database: http://wwwuser.gwdg.de/~compbiol/uniclust/2016_09/; this is also the database I used in our experiments. We are developing a new pipeline for concatenating heterodimers, so I don't really plan to fix the bugs any time soon.
