### ISSUE TITLE
'*/external/TaxTree'  not found!

### ISSUE THREAD

**Issue by unimqz** [zw2x/glinter#2]
Hi! When I run the examples by glinter, this error has occured in A3M_SpecBloc! 
I download the taxonomy database as you pointed.
Then, another error 'ERROR -> each bottom_digit shall contain only 7 columns separated with ' ' -> 1198' occured.
I noticed what you mentioned that the format of the uniclust database.
The version of my uniclust database is uniclust30_2018_08. 
May I ask if the avove errors is due to the different database?
Thank you!

**Comment by zw2x** [comment]
Hi,
Can you post the error message you saw and the headers in the a3m file?

**Comment by unimqz** [comment]
Thank you for your reply!
The first error is 'msa_num=5386
file /home/xxx/glinter-master/external/TaxTree not found!'
Then I renamed the taxonomy database you pointed to the 'TaxTree' .
Next the error is:
'msa_num=5386
ERROR -> each bottom_digit shall contain only 7 columns separated with ' ' -> 1198
msa_num=5386
ERROR -> each bottom_digit shall contain only 7 columns separated with ' ' -> 1198
file /home/xxx/glinter-master/examples//1a59A:1a59B/1a59A/1a59A.a3m_sb not found!
file /home/xxx/glinter-master/examples//1a59A:1a59B/1a59A:1a59B.a3m_cc not found!
/home/xxx/glinter-master/preprocess/MSA/concat_msa.sh: line 24: 12821 Segmentation fault      (core dumped) $GLINT_ROOT/external/meff_cdhit -S 0.65 -c 0 -i $srcdir/$name.a3m_cc > $srcdir/$name.meff'

The 1a59A.a3m file:
>1a59A
EPTIHKGLAGVTADVTAISKVNSDTNSLLYRGYPVQELAAKCSFEQVAYLLWNSELPNDSELKAFVNFERSHRKLDENVKGAIDLLSTACHPMDVA
>tr|A0A1X6XVY3|A0A1X6XVY3_9CORY Citrate synthase OS=Corynebacterium xerosis OX=1725 GN=FM103_14400 PE=3 SV=1
TTEIRKGLNGVVADVTAVSKVNPETNSLLYRGYPVPELAATQPFEAVAHLLWTGELPTAEETAAATRHERSHRALATEVKAAMDSLPTTCHPMDA
>tr|A0A1I7ML75|A0A1I7ML75_9MICC Citrate synthase OS=Micrococcus terreus OX=574650 GN=SAMN04487966_104259 PE=3 SV=1

The 1a59A.a3m_ng file:
>1a59A | 1940 / 377 -> 5.145889 
EPTIHKGLAGVTADVTAISKVNSDTNSLLYRGYPVQELAAKCSFEQVAYLLWNSELPNDSELKAFVNFERSHRKLDENVKGAIDLLSTACHPMDVA>tr|C7MBT9|C7MBT9_BRAFD Citrate synthase OS=Brachybacterium faecium (strain ATCC 43885 / DSM 4810 / NCIB 9860) OX=446465 GN=Bfae_12020 PE=3 SV=1 | 1428 / 377 -> 3.787798 
-PEIRKGLNGVVADTTAISKVNPETNSLLYRGYPVPQLAATQSIEAVAHLLWTGELPDEQELAQAVAHERSHRDLVPQVRAAMDSLPTTCHPMDAV>tr|A0A0Q9MEQ4|A0A0Q9MEQ4_9MICC Citrate synthase OS=Arthrobacter sp. Soil761 OX=1736400 GN=ASG79_15860 PE=3 SV=1 | 1416 / 377 -> 3.755968 
-TDIRKGLAGVVVDYTAVSKVNPDTNSLLYRGYPVQELAARCSFEEVAYLLWNAELPSEGELAEFTARERASRSLDPALKMIIDALPKTAHPMDVCRT

**Comment by zw2x** [comment]
It seems that the headers in a3m are missing ">". I am able to parse the headers you provide after it is formatted like:

\>header
seq
\>header2
seq2

You can send me your complete a3m file if you still run into issues after correcting the format.

**Comment by unimqz** [comment]
The header contains ">" in the .a3m file.   
[1a59A.a3m.txt](https://github.com/zw2x/glinter/files/9173331/1a59A.a3m.txt)
[1a59A.a3m_ng.txt](https://github.com/zw2x/glinter/files/9173332/1a59A.a3m_ng.txt)
[1a59B.a3m.txt](https://github.com/zw2x/glinter/files/9173333/1a59B.a3m.txt)
[1a59B.a3m_ng.txt](https://github.com/zw2x/glinter/files/9173334/1a59B.a3m_ng.txt)

**Comment by zw2x** [comment]
I can successfully build .a3m_ng files from your .a3m files and .a3m_cc files from your a3m_ng files. So I am not exactly sure what the bug really is. It is possible the database you downloaded is corrupted, so you may try to re-download [the database](https://zenodo.org/record/5172929#.Yt61cZHMJhE) and then try to run the command in concat_msa.sh step by step.
